services:
  radio-bot:
    build: .
    container_name: radio-bot
    env_file:
      - .env
    volumes:
      - ./stations.json:/app/stations.json
      - ./logs:/app/logs
    restart: unless-stopped
